### ISSUE TITLE
Bypass is not working, Still showing 2000 word limit

### ISSUE THREAD

**Issue by jon4short** [riad-azz/bing-ai-no-limit#1]
I loaded the script as instructed, the Bypass is not working. I still see 2000 word limit.

**Comment by jon4short** [comment]
I uninstalled the Dev Channel of Edge and Installed the regular one.

**Comment by riad-azz** [comment]
![image](https://user-images.githubusercontent.com/80968727/228991403-95e2fa30-37e0-48a8-8c75-09b047545f9e.png)

it seems to be working fine on the dev channel for me, but thanks i will update the README to notify future users that dev channel might cause a problem
