### ISSUE TITLE
it breaks when choosing different conversation style.

### ISSUE THREAD

**Issue by bigplayer-ai** [riad-azz/bing-ai-no-limit#3]
it breaks when choosing different conversation style.

**Comment by riad-azz** [comment]
can you be more specific? because it seems to be working just fine. Maybe you are using an older version?

![preview](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/24431a51-58a2-40e1-8a6b-8952d36745b2)

**Comment by bigplayer-ai** [comment]
Thanks it just worked, I had it wrong set up.
