### ISSUE TITLE
it stopped working, I think Microsoft patched this tweak.

### ISSUE THREAD

**Issue by bigplayer-ai** [riad-azz/bing-ai-no-limit#4]
it stopped working, I think Microsoft patched this tweak.

**Comment by riad-azz** [comment]
Worry not my friend. I have patched their tweak too 😉

![image](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/b1819ca7-1020-4f4f-8d7a-276c4dfc1177)

have a good day

**Comment by DevX-Cipher** [comment]
it does not seem to work either in August
