### ISSUE TITLE
Tweask dont work

### ISSUE THREAD

**Issue by DevX-Cipher** [riad-azz/bing-ai-no-limit#5]
hi the tweak dont seem to work anymore

**Comment by DevX-Cipher** [comment]
ok figured it out works on the browser not the plugin that was made

**Comment by riad-azz** [comment]
Hey there, Do you still have the problem of it not working or is it solved??

![image](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/5def0ed4-e64b-4f36-9502-eec66f0f59c9)

It stopped working for me too but it was because the extension got disabled from the browser after the last edge update. All i had to do was enabled it again here:

![Untitled](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/63e82681-a994-47bc-91f8-fe0925a5a6ce)

Please let me know if it's still not working for you.

**Comment by DevX-Cipher** [comment]
yes it was working i was thinking about the built in one also any chance of removing the convisation limit

**Comment by riad-azz** [comment]
Sadly I don't think its possible to remove the conversation limit. I tried searching for the variable storing the conversation count on the client side but couldn't find anything, so my guess is that its cached on the server side with the conversation id.

As for the built in one, I would need to modify the browser it self to add it in there so its not possible for me.

**Comment by DevX-Cipher** [comment]
yer i dont think is because you need the source code hhaha i found the convisation counter but it seems that it use javascript

**Comment by modz2014** [comment]
yer i just tried to post over 4000 words to bing and pasting it to bing chat limit it to 2000 still

**Comment by DevX-Cipher** [comment]
ok so i gave it over 4000 say a hole code and fails so there must be a limit it can handle for convisation

**Comment by riad-azz** [comment]
Are you talking about the 0/30 limit? if so then how did you change it?

**Comment by DevX-Cipher** [comment]
no i have not change it yet sorry its confusing atm the unlmited text you does not work if you have say 6000 words

**Comment by riad-azz** [comment]
Oh, you are talking about my extension?
In that case then yes, if you send too much text then the AI will fail the request as mentioned in the readme:

![image](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/5cf406cf-cd37-47af-96c5-b5c41653af57)

**Comment by DevX-Cipher** [comment]
i tried 10k and it faild the conntection

**Comment by riad-azz** [comment]
I don't know what you tried to input but here is proof that it worked. I copy pasted python docs from [What’s New In Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#pep-657-fine-grained-error-locations-in-tracebacks) and asked it to explain it, here is the result:

![1](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/5102a8c4-283e-4b7f-bcb3-d469fc67cb78)

![2](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/19bfa88c-b855-4b0f-8063-bbc8d703f6c4)

![3](https://github.com/riad-azz/bing-ai-no-limit/assets/80968727/4b3c9648-1d82-4ade-af65-d356918a16ba)

As you can see 11668 character and it still works fine,  maybe your input is the problem.

**Comment by DevX-Cipher** [comment]
im not sure seems werid how i get a server connection error works find if i dont past 4000
