### ISSUE TITLE
Switching conversation styles resets the character limit

### ISSUE THREAD

**Issue by epic0421** [riad-azz/bing-ai-no-limit#6]
When the conversation style is changed, any field that already contains 4000 characters or more will not allow additional characters to be entered.

**Comment by riad-azz** [comment]
Hey there Epic0421,

Can you please provide more information or a picture/gif showcasing the problem?

**Comment by epic0421** [comment]
![showcase](https://github.com/riad-azz/bing-ai-no-limit/assets/85042398/021d2e6b-6689-4fdf-b4d4-97bc55c2671e)

**Comment by riad-azz** [comment]
Fixed with the latest commit : https://github.com/riad-azz/bing-ai-no-limit/commit/3ef16edbf5388972dc3703a617238d8a9e3f097d
